micronaut:
  server:
    #dualProtocol: true
    port: 8080
    cors:
      enabled: true
  application:
    name: raspi-esp01-endpoint
  metrics:
    enabled: true

datasources:
  default:
    url: jdbc:postgresql://192.168.100.124:5432/iot_db
    driverClassName: org.postgresql.Driver
    username: henninb
    password: monday1
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
